version: '2'

services:
  jenkins:
    image: campbel/jenkins:latest
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "jenkins:/var/jenkins_home"

volumes:
  jenkins: